add | recrut role
starfort-station/station-14 pull request #128
Opened 2023-05-03 18:11 UTC by MetalSage

![изображение](https://user-images.githubusercontent.com/74924875/236006340-1192ad54-b64f-44bd-9479-8e95cab7c484.png)
![изображение](https://user-images.githubusercontent.com/74924875/236006354-1b3f6df1-837e-4cbe-b607-042807b4b6ee.png)

2023-05-03 18:13 UTC, kzhanik commented
А че буква "К", а не "А"?

2023-05-03 18:32 UTC, MetalSage commented
> А че буква "К", а не "А"?

Вопросы к 778, я изначально А делал

2023-05-04 03:09 UTC, kzhanik requested changes
Привел тебе ошибки, исправь пожалуйста. А ещё я не понял прикола с двумя АВД, также не ясно, у тебя в одном месте командир экспедиторов, в другом сержант. Путаница же.

2023-05-04 03:09 UTC, kzhanik commented on Resources/Locale/ru-RU/Starfort/job/job-names.ftl
> +job-name-field-engineer = Полевой инжинер
Сука, инженер блять, инжЕнер!

2023-05-04 03:09 UTC, kzhanik commented on Resources/Locale/ru-RU/Starfort/prototypes/entities/objects/devices/pda.ftl
> +    .desc = Пока что ничем не пахнет, кажеться он был недвано получен.
Сука, кажется без Ь, НЕДАВНО, блять.

2023-05-04 03:09 UTC, kzhanik commented on Resources/Locale/ru-RU/Starfort/job/job-description.ftl
> +job-description-field-recrut = Изучите основы экспедиций, помогайте своей команде достич общих успехов.
ДОСТИЧЬ, ДОСТИЧЬ КАРЛ

2023-05-04 03:09 UTC, kzhanik commented on Resources/Locale/ru-RU/Starfort/job/job-names.ftl
> +job-name-ccagent = Агент внутренних дел
Агент Внутренних Дел. Заглавные буквы.

2023-05-04 03:09 UTC, kzhanik commented on Resources/Locale/ru-RU/Starfort/job/job-names.ftl
> +JobCentralCommandOfficial = Агент внутрених дел
Я не понял, а че тут два АВД

2023-05-04 03:09 UTC, kzhanik commented on Resources/Locale/ru-RU/Starfort/prototypes/entities/objects/misc/identification_cards.ftl
> +ent-CCAgentIDCard = ID карта агента внутрених дел
ВНУТРЕННИХ

2023-05-04 05:14 UTC, 778b commented on Resources/Locale/ru-RU/Starfort/job/job-names.ftl
> +JobCentralCommandOfficial = Агент внутрених дел
возможно потому что это JobTimer?

2023-05-04 10:39 UTC, 778b approved these changes

2023-05-04 11:19 UTC, kzhanik approved these changes
ОМГ, у меня попросили оценку!? Ну что, мне всё нравится. ❤

2023-05-04 11:22 UTC, kzhanik requested changes
О нет, грамматика хочет выпрыгнуть.

2023-05-04 11:22 UTC, kzhanik commented on Resources/Locale/ru-RU/Starfort/prototypes/entities/objects/devices/pda.ftl
> +ent-CCAgentPDA = КПК агента внутрених дел
Где сука заглавные буквы?

2023-05-05 04:32 UTC, kzhanik commented
> дак нет смысла в заглавных буквах, все профессии пишутся с маленькой, это уже пофиксили и в след обнове залетит

В смысле? Как он пофиксил это если ПР ещё не одобрили с фиксами?

2023-05-05 05:08 UTC, 778b commented
> > дак нет смысла в заглавных буквах, все профессии пишутся с маленькой, это уже пофиксили и в след обнове залетит
> 
> В смысле? Как он пофиксил это если ПР ещё не одобрили с фиксами?

корваксы уже смерджили это, значит как только мы позаимствуем у них перевод, то у нас тоже все обновится

2023-05-05 05:19 UTC, kzhanik commented
> корваксы уже смерджили это, значит как только мы позаимствуем у них перевод, то у нас тоже все обновится

Ок, тогда мерджу?

2023-05-05 05:31 UTC, 778b commented
> > корваксы уже смерджили это, значит как только мы позаимствуем у них перевод, то у нас тоже все обновится
> 
> Ок, тогда мерджу?

угу

2023-05-05 05:32 UTC, merged