add | portable substation
starfort-station/station-14 pull request #152
Opened 2023-05-08 09:32 UTC by MetalSage

## О PR'е
- Добавил портативную подстанцию

**Медиа**

* [x] Я добавил скриншоты/видео к этому PR, демонстрирующие его изменения в игре **или** этот PR не требует демонстрации в игре. 

**Проверка**

* [x] В ходе проверки на локальном сервере, я не нашёл каких-либо багов, вызванных моим PR'ом.

closed #141

2023-05-08 10:25 UTC, kzhanik commented
Где медиа?

2023-05-15 20:31 UTC, 778b commented
Тут спрайт добавлен #170 
И лучше измени название на какое-нибдь интересное, типо энерго ячейка это супер банально а вот "ПУЗА - Портативное Устройство Зарядки Аппаратуры" уже звучит и всем классно становится

2023-05-16 15:11 UTC, 778b requested changes
![image](https://github.com/starfort-station/station-14/assets/33431126/d99d0f0d-9705-45c2-9196-42472ba37658)
Нет коллизии у аккума
Не сменил имя

2023-05-16 15:11 UTC, kzhanik requested changes
Нету медиа, добавь его

2023-05-18 12:58 UTC, closed without merging