Добавил коробку с магазинами и коробки с патронами для тяжелого лектера
starfort-station/station-14 pull request #171
Opened 2023-05-16 15:08 UTC by Gerkada

## О PR'е
Добавил коробку с магазинами тяжелого лектера, а так же большую и маленькие коробки с патронами к нему же

**Проверка**

* [x] В ходе проверки на локальном сервере, я не нашёл каких-либо багов, вызванных моим PR'ом.

2023-05-16 15:10 UTC, kzhanik commented
Где медиа?

2023-05-16 15:10 UTC, kzhanik commented
Без медиа мерджа не будет

2023-05-16 15:10 UTC, kzhanik commented
И точка

2023-05-16 15:12 UTC, kzhanik requested changes
ЖДУ МЕДИА

2023-05-16 15:37 UTC, Gerkada commented
> Без медиа мерджа не будет

А я говорю, что будет, ниибёт

2023-05-16 15:45 UTC, 778b commented
надо конфликты пофиксить

2023-05-16 21:04 UTC, Gerkada commented
> надо конфликты пофиксить

Те, которые гит высрал?

2023-05-17 05:20 UTC, 778b commented
да, 
![image](https://github.com/starfort-station/station-14/assets/33431126/8aa0b46f-fed2-42ee-9790-5b79c63592f3)

2023-05-17 07:27 UTC, 778b approved these changes

2023-05-17 07:28 UTC, merged