Tweak | Bug fixes on Eclipse and new things. New job spawn for recrut.
starfort-station/station-14 pull request #219
Opened 2023-05-27 20:40 UTC by kzhanik

## О PR'е

### Карта

- Исправлен баг с отсутствием места спавна ГСБ, Смотрителя, утилизаторов и новобранца.
- Добавил пассивную вентиляцию с объёмным газовым насосом, чтобы можно было наполнять канистры воздухом.
- Добавил факс на шаттл экспедиторов для связи со станции
- Добавил раковину, дренаж, влажную тряпку и ведро в генераторную для уборки на шаттле экспедиторов.

### Прототипы

- Добавил job spawn для рекрута со своим спрайтом.
- Исправлен баг с мануалом ОБР
- Добавлен СРП Экспедиторов (не спавнится раундстартом на Eclipse)

**Медиа**

* [ ] Я добавил скриншоты/видео к этому PR, демонстрирующие его изменения в игре **или** этот PR не требует демонстрации в игре.  

**Проверка**

* [x] В ходе проверки на локальном сервере, я не нашёл каких-либо багов, вызванных моим PR'ом.

* [x] Я сделал локализацию для моих прототипов в PR'е **или** я не делал прототипы в этом PR'е.

2023-05-27 22:28 UTC, 778b requested changes

2023-05-27 22:28 UTC, 778b commented on Resources/Prototypes/Starfort/Catalog/Fills/Paper/manuals.yml
> +  id: PaperWrittenERTmanual
ты переименовал айдишник, остались предметы которые ссылаются на старый айдишник, например стартовое снаряжение ОБР

2023-05-27 22:37 UTC, 778b requested changes

2023-05-27 22:37 UTC, 778b commented on Resources/Maps/eclipse.yml
> +  - uid: 15417
зачем вытяжка на шатле? Типо не отнимает работу у уборщика?

2023-05-27 22:37 UTC, 778b commented on Resources/Maps/eclipse.yml
> +- proto: SinkStemlessWater
Бля, раковина, ведро, швабра на шаттл экспедиторов? Уборщик скажет спасибо, теперь за него работают солдаты, тоже не ЛРП?

2023-05-27 22:37 UTC, 778b commented on Resources/Maps/eclipse.yml
> +- proto: SpawnPointParamedic
Спавн парамеде не нужен, его нет на эклипсе как доступная роль

2023-05-28 04:44 UTC, kzhanik commented on Resources/Prototypes/Starfort/Catalog/Fills/Paper/manuals.yml
> +  id: PaperWrittenERTmanual
Решено

2023-05-28 04:44 UTC, kzhanik commented on Resources/Maps/eclipse.yml
> +  - uid: 15417
Удалил дренаж.

2023-05-28 04:44 UTC, kzhanik commented on Resources/Maps/eclipse.yml
> +- proto: SpawnPointParamedic
Удалено.

2023-05-28 04:45 UTC, kzhanik commented on Resources/Maps/eclipse.yml
> +- proto: SinkStemlessWater
Тряпка и ведро будут перенесены в туалет на станцию. Раковина удалена.

2023-05-28 08:43 UTC, 778b approved these changes

2023-05-28 08:43 UTC, merged