translate | upstream 01:06
starfort-station/station-14 pull request #223
Opened 2023-06-01 21:25 UTC by MetalSage

## О PR'е
- Перевод #221 

**Медиа**

* [ ] Я добавил скриншоты/видео к этому PR, демонстрирующие его изменения в игре **или** этот PR не требует демонстрации в игре.  

**Проверка**

* [ ] В ходе проверки на локальном сервере, я не нашёл каких-либо багов, вызванных моим PR'ом.

* [ ] Я сделал локализацию для моих прототипов в PR'е **или** я не делал прототипы в этом PR'е.

2023-06-02 07:29 UTC, kzhanik commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/lockers/suit_storage.ftl
> +    .suffix = Ancient EVA
Алё, мы шпрехе ~~зе дольч~~ руссич

2023-06-02 07:34 UTC, kzhanik requested changes
Комменитарии оставил, жду фидбэка и фиксов. Слава Рамилесу!

2023-06-02 07:34 UTC, kzhanik commented on Resources/Locale/ru-RU/station-events/events/cargo-gifts.ftl
> +cargo-gifts-event-announcement = Поздравляем! { $sender } отправил { $description } для { $dest }.
Почему я решил передалть данную херню? Потому что получалось так: НаноТрахен отправил небольшая вечеринка с пиццей для бар. Ну и люди побежали в бар, а там нихуя. Поэтому бы добавить сюда разъяснение что заказ надо принимать сука в карго. Кхм.

2023-06-02 07:34 UTC, kzhanik commented on Resources/Locale/ru-RU/station-events/events/cargo-gifts.ftl
> +cargo-gift-dest-supp = горузового отдела
Ошибка, исправь.

2023-06-02 07:34 UTC, kzhanik commented on Resources/Locale/ru-RU/station-events/events/cargo-gifts.ftl
> +cargo-gift-security-guns = ящик оружия
Ну смотри, в подарок входит не один ящик. Надо написать либо припасы (множественное число) либо ещё как перефразировать.

2023-06-02 07:34 UTC, kzhanik commented on Resources/Locale/ru-RU/traits/traits.ftl
> +trait-uncloneable-name = Не клонируемый
Согласно правилам русской орфографии, правильное написание будет "неклонируемый" — слитно, без дефиса.

2023-06-02 13:36 UTC, kzhanik requested changes
Алё, один разговор ещё ты не закрыл. Чини давай.

2023-06-02 13:41 UTC, MetalSage commented
> Алё, один разговор ещё ты не закрыл. Чини давай.

Что я не закрыл?

2023-06-02 13:45 UTC, kzhanik commented
> Что я не закрыл?

![Screenshot_813](https://github.com/starfort-station/station-14/assets/102734625/acfeca77-b38e-48f3-9ede-ac9763239d75)

2023-06-04 05:31 UTC, kzhanik commented
Поскольку @MetalSage поленился делать как я сказал, я сам это сделал.

2023-06-04 05:32 UTC, kzhanik approved these changes

2023-06-04 05:32 UTC, merged