Add hellblossom & change price exotic seeds
starfort-station/station-14 pull request #249
Opened 2023-06-20 13:39 UTC by Darkaint1

## О PR'е

**Прототипы**
* Добавил новое растение "Hellblossom"

**Изменения**
* Изменена стоимость ящика экзотических семян с 1000 до 3000

**Медиа**

![image](https://github.com/starfort-station/station-14/assets/81798163/da187693-b6be-4f56-8e08-3e1a9d16df12)

* [x] Я добавил скриншоты/видео к этому PR, демонстрирующие его изменения в игре **или** этот PR не требует демонстрации в игре.  

**Проверка**

* [x] В ходе проверки на локальном сервере, я не нашёл каких-либо багов, вызванных моим PR'ом.

* [x] Я сделал локализацию для моих прототипов в PR'е **или** я не делал прототипы в этом PR'е.

2023-06-20 13:47 UTC, kzhanik requested changes
Надо делать ПР на мердж с веткой Dev :trollface:

2023-06-20 16:26 UTC, Darkaint1 commented
Понял принял, сейчас исправим

2023-06-20 19:20 UTC, closed without merging

2023-06-20 20:08 UTC, Darkaint1 commented
Закрыл ветку в связи с её проблемами и моей криворукостью.

2023-06-21 14:09 UTC, Darkaint1 commented
Новая PR открыт, жду одобрения