Create CentComm shuttle
starfort-station/station-14 pull request #308
Opened 2023-08-06 18:44 UTC by tanatotrb

## О PR'е

Замаппила новый шаттл для Центрального Командования, которым смогут пользоваться как ОБР, ПЦК, так и другие представители Центрального Командования.
Шаттл имеет Инженерный отдел, Медицинский отдел (химическое оборудование, клонёрка, перевязочная), отдел Службы Безопасности (изолятор), мостик, бар.

**Медиа**

![ccs](https://github.com/starfort-station/station-14/assets/138137497/0541f685-ba5b-4d16-a1c6-29f2df46aa51)

* [X] Я добавил(а) скриншоты/видео к этому PR, демонстрирующие его изменения в игре **или** этот PR не требует демонстрации в игре.  

**Проверка**

* [X] В ходе проверки на локальном сервере, я не нашёл/нашла каких-либо багов, вызванных моим PR'ом.

* [X] Я сделал(а) локализацию для моих прототипов в PR'е **или** я не делал(а) прототипы в этом PR'е.

2023-08-06 20:52 UTC, 778b commented
слева снизу ускорители не запитаны и интересно как помойки соединены

2023-08-09 10:44 UTC, kzhanik requested changes
Поскольку это шаттл, он должен сохраняться как **grid**, при помощи команды `savegrid`.

2023-08-13 12:58 UTC, kzhanik commented
Воздушная сигнализация отвалилась, нужно починить. Переподключи снова всё заново. А ну и ещё меня встретило кресло в бриге шаттла.

![Content Client_qeyVcsaSbS](https://github.com/starfort-station/station-14/assets/102734625/292ce627-5bd6-4492-9a26-a06ad0d242b8)

2023-08-13 12:59 UTC, kzhanik requested changes
Воздушная сигнализация отвалилась, нужно починить. Переподключи снова всё заново. А ну и ещё меня встретило кресло в бриге шаттла.

![image](https://github.com/starfort-station/station-14/assets/102734625/c327b0b0-75c7-4a71-a90e-417bd9a353f9)

2023-08-13 14:39 UTC, closed without merging