Added combat medipen
starfort-station/station-14 pull request #67
Opened 2023-04-22 17:42 UTC by fedKotikeD

closes #66 

Добавляет боевой медипен как в исью #66

2023-04-22 18:41 UTC, 778b requested changes

2023-04-22 18:41 UTC, 778b commented on Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
> +    tags: [Expedition]
```
  - type: Tag
    tags: [Expedition]
```
Такого тэга нет, просто убери компонент тэга

2023-04-22 18:41 UTC, 778b commented on Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
> +  - type: Sprite
Компонент Sprite и SolutionContainerVisuals и Appearance если ты используешь состояния из космомедипена то лучше возьми его в наследники и убери эти поля

2023-04-22 19:19 UTC, 778b approved these changes

2023-04-22 19:20 UTC, 778b requested changes
А стоп, еще перевод нужен

2023-04-22 19:20 UTC, fedKotikeD commented
> А стоп, еще перевод нужен

А, понял. Сделаю завтра

2023-04-23 09:54 UTC, 778b approved these changes

2023-04-23 10:01 UTC, merged