Xeno radio
starfort-station/station-14 pull request #68
Opened 2023-04-22 17:54 UTC by fedKotikeD

closes #64

Я уверен, что я забыл что-то сделать поэтому драфт

2023-04-22 17:54 UTC, fedKotikeD commented
Ща сделаю локализацию

- [ ] Если я уже сделал, тут будет галочка

2023-04-22 18:01 UTC, fedKotikeD commented
Что еще нужно добавить? Или так будет работать?

2023-04-22 18:03 UTC, MetalSage commented
> Что еще нужно добавить? Или так будет работать?

так ты ничего не сделал

2023-04-22 18:03 UTC, fedKotikeD commented
> > Что еще нужно добавить? Или так будет работать?
> 
> так ты ничего не сделал

В смысле?

2023-04-22 18:48 UTC, 778b requested changes

2023-04-22 18:48 UTC, 778b commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +  - type: ActiveRadio
Нужен компонент EncryptionKey чтобы они могли писать в свой чат, а для этого видимо придется сделать сам EncryptionKey

2023-04-22 18:49 UTC, fedKotikeD commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +  - type: ActiveRadio
Ых, жалко. Ну ладно, завтра сделаю

2023-04-23 10:27 UTC, fedKotikeD commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +  - type: ActiveRadio
> Нужен компонент EncryptionKey чтобы они могли писать в свой чат, а для этого видимо придется сделать сам EncryptionKey

Сделал, но вроде как нужен еще спрайт для него и компонент ксено

2023-04-30 16:05 UTC, fedKotikeD commented
Короче у меня нет интернета и времени, поэтому пусть это делают другие

2023-04-30 16:05 UTC, closed without merging