Add Comander
starfort-station/station-14 pull request #74
Opened 2023-04-22 20:38 UTC by fedKotikeD

closes #72 

Тут так много коммитов ибо я сначала написал comMander, а там оказалась одна M. Пипец короче. А и да, @MetalSage с тебя спрайты одежды и тд

2023-04-23 06:06 UTC, 778b requested changes

2023-04-23 06:06 UTC, 778b commented on Resources/Prototypes/Roles/Jobs/Expedition/field_comander.yml
> +  - External
забыл про доступ в оружейку

2023-04-23 06:59 UTC, fedKotikeD commented on Resources/Prototypes/Roles/Jobs/Expedition/field_comander.yml
> +  - External
Ок, добавлю

2023-04-23 07:02 UTC, fedKotikeD commented on Resources/Prototypes/Roles/Jobs/Expedition/field_comander.yml
> +  - External
> забыл про доступ в оружейку

Поправил

2023-04-23 09:49 UTC, fedKotikeD commented
Я дурачина, не туда сделал локализацию. Ветку забыл поменять. АХАХАХАХАХХА

2023-04-23 15:34 UTC, fedKotikeD commented
Как смогу, сделаю ему спрайты. Надо будет мне потом замутить шкаф и айди карту с доступом

2023-04-24 07:14 UTC, 778b commented
> Как смогу, сделаю ему спрайты. Надо будет мне потом замутить шкаф и айди карту

Спрайт шкафа возьми солдатский, айди карту Хоса но цвета поменяй просто на наши, как у солдата

2023-04-24 08:18 UTC, kzhanik commented
А почему commander с одной M?

2023-04-24 09:02 UTC, fedKotikeD commented
> > Как смогу, сделаю ему спрайты. Надо будет мне потом замутить шкаф и айди карту
> 
> Спрайт шкафа возьми солдатский, айди карту Хоса но цвета поменяй просто на наши, как у солдата

Карту я ему сделал как у трупера но поменял цвета на белый и вместо щита поставил звезду как у карты кэпа. Спрайты залью все чуть позже

2023-04-24 14:14 UTC, fedKotikeD commented
Осталось шкафчик и вынимаю из драфта

2023-04-24 16:42 UTC, fedKotikeD commented
@778b обязательно делать отдельный шкафчик для командира или так сойдет?

2023-04-24 16:53 UTC, 778b commented
> @778b обязательно делать отдельный шкафчик для командира или так сойдет?

ну ты вроде как хотел спрайты делать, или уже не хочешь?

2023-04-24 17:12 UTC, fedKotikeD commented
> > @778b обязательно делать отдельный шкафчик для командира или так сойдет?
> 
> ну ты вроде как хотел спрайты делать, или уже не хочешь?

лучше думаю это уже закрыть и другим заняться

2023-04-24 17:25 UTC, 778b requested changes

2023-04-24 17:25 UTC, 778b commented on Resources/Prototypes/Roles/Jobs/Expedition/field_comander.yml
> +    ears: ChotlingHeadsetExpedition
ошибка в слове ChotlingHeadsetExpedition

2023-04-24 17:32 UTC, 778b requested changes
А где meta.json у спрайтов?

2023-04-24 17:33 UTC, fedKotikeD commented
> А где meta.json у спрайтов?

уууу, сделаю

2023-04-24 17:34 UTC, 778b requested changes

2023-04-24 17:34 UTC, 778b commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +  - type: PresetIDCard
ошибка в слове PresetIDCard

2023-04-24 17:35 UTC, fedKotikeD commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +  - type: PresetIDCard
где

2023-04-24 17:36 UTC, 778b commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +  - type: PresetIDCard
где-то

2023-04-24 17:37 UTC, fedKotikeD commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +  - type: PresetIDCard
> где-то

я не вижу

2023-04-24 17:51 UTC, 778b requested changes

2023-04-24 17:51 UTC, 778b commented on Resources/Prototypes/Roles/Jobs/Expedition/field_comander.yml
> +  id: FieldCommaderGear
ошибка в слове FieldCommaderGear, подсказка: посмотри как указано в прототипе роли

2023-04-26 16:26 UTC, 778b requested changes
короче еще этот поправь и мету добавь и сразу мержу, конфликты сам решу

2023-04-26 16:26 UTC, 778b commented on Resources/Prototypes/Roles/Jobs/Expedition/field_commander.yml
> +    belt: ClothingBeltAssault
вместо пояса штурмовика исользуй расгрузку #98

2023-04-26 16:26 UTC, 778b commented on Resources/Prototypes/Roles/Jobs/Expedition/field_commander.yml
> +  supervisors: job-supervisors-rd
подчиняется капитану

2023-04-26 18:32 UTC, merged